import React, { useState, useEffect } from 'react';
import { Loader, Card, FormField } from '../components';
import { useFetchPosts, useSearch } from '../hooks';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className="mt-5 text-xl font-bold uppercase text-[#6499ff]">{title}</h2>
  );
};

const Home = () => {
  const { loading, allPosts } = useFetchPosts();
  const { searchText, handleSearchChange, searchResults } = useSearch(allPosts);
  return (
    <section className="mx-auto max-w-7xl">
      <div>
        <h1 className="text-[32px] font-extrabold text-[#222328]">
          The Community Showcase
        </h1>
        <p className="mt-2 max-w-[500px] text-[14px] text-[#888a75] ">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search posts"
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="item-center flex justify-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="mb-3 text-xl font-medium text-[#666e75]">
                Showing results of{' '}
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}
            <div className="sm:gird-cols-3 sx:grid-cols-2 grid grid-cols-1 gap-3 lg:grid-cols-4">
              {searchText ? (
                <RenderCards
                  data={searchResults}
                  title="No search results found"
                />
              ) : (
                <RenderCards data={allPosts} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
